import { NextResponse } from 'next/server';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

/**
 * Serves cross-analysis insights from the data/insights.json file.
 * These are generated by the BigBrain + Google Ads sync scripts.
 */
export async function GET() {
  const insightsPath = join(process.cwd(), 'data', 'insights.json');

  if (!existsSync(insightsPath)) {
    return NextResponse.json({
      insights: [],
      message: 'No insights file found. Run scripts/sync_bigbrain_data.py first.',
    });
  }

  try {
    const raw = readFileSync(insightsPath, 'utf-8');
    const data = JSON.parse(raw);
    return NextResponse.json({
      insights: data.insights || [],
      generatedAt: data.generated_at,
      source: data.source,
    });
  } catch (error) {
    return NextResponse.json({ insights: [], error: 'Failed to parse insights.json' }, { status: 500 });
  }
}
